### ISSUE TITLE
why no helpers?

### ISSUE THREAD

**Issue by vitaly-t** [cefaci/super-simple-pg-dao#1]
Why didn't you make use of the [helpers](https://vitaly-t.github.io/pg-promise/helpers.html)? They are the most logical choice for batch inserts.

[See this example](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise).

**Comment by cefaci** [comment]
Yeah they are awesome, saw them(!!), but when I started the plugin the batch insert logic there weren't the helpers and I just wanted json inserts and I was using the old format, e.g.

return t.batch([
            t.none('INSERT INTO Users(name, age) VALUES($1, $2)', ['John', 23]),
           ...
        ]);

When I started it years ago, I wanted something for my json data which sets only the columns needed for a transaction insert and doing "cascade" inserts with the returning foreign keys (where no batch is working, maybe it is misleading wording in my doc).
The second case I use it for are the more complex reads https://github.com/cefaci/super-simple-pg-dao#query and in the beginning I didn't like any DAO libs I found.

Your pg-promise lib is awesome, love it!
